language: perl
sudo: false
perl:
  - "5.8"
  - "5.12"
  - "5.16"
  - "5.20"
  - "5.24"

install:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
  - cpanm --quiet --notest --skip-satisfied Perl::Critic@1.125 Test::Perl::Critic@1.03
  - cpanm --quiet --installdeps --notest .

script:
  - perl Build.PL && ./Build build
  - prove -r xt
  - cover -test

after_success:
  - cover -report codecov

