name = "JSON-Types-Flexible"
badges = ["travis", "codecov"]
authority="cpan:PINE"
authors = ["Pine Mizune <pinemz@gmail.com>"]
license="mit"

module_maker="ModuleBuildTiny"

[Metadata]
x_static_install = 1
